config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'
  get 'home/top' => 'home#top'
  get 'home/search' => 'home#search' 
  get 'home/about' => 'home#about'

  get 'articles/search' => 'articles#search'
  get "users/:id/likes" => "users#likes"
  get "articles/:id/likes" => "articles#likes"

  resources :articles, only: [:create, :index, :new, :show, :edit, :update, :destroy]do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "log_in", :to => "users/sessions#new"
    get "log_out", :to => "users/sessions#destroy" 
  end
  
  get "users/show/:id" => "users#show"
  resources :users
end

app/models/article.rb
class Article < ApplicationRecord

    belongs_to :user
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    has_many :comments

    validates :content, {presence: true}
    validates :title, {presence: true}


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :authenticate_user!, except: [:search, :show]

    

    def new
        @article = Article.new
    end

    def search
        if params[:search] == nil
            @search = Article.includes(:user)
        elsif params[:search] == ""
            @search = Article.includes(:user)
        else
            @search = Article.includes(:user).where("title LIKE ? ",'%' + params[:search] + '%').or(Article.where("place LIKE ? ", "%" + params[:search] + "%"))
        end
    end

    def create
        @article = current_user.articles.create(article_params)
        user = User.find(@article.user_id)
        if @article.save
            flash[:info] = "新規投稿しました"
            redirect_to(user)
        else
            flash[:alert] = "投稿に失敗しました"
            redirect_to action:"new"
        end
    end

    def show
        @article = Article.find(params[:id])
        @like = Like.new
        @comments = @article.comments
        @comment = Comment.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        article = Article.find(params[:id])
        article.update(article_params)
        redirect_to article
    end

    def destroy
        article = Article.find(params[:id])
        article.delete
        user = User.find(article.user_id)

        redirect_to(user)
    end

    private
    def article_params
        params.require(:article).permit(:title, :place, :content)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= render 'header' %>
<div class="d-flex align-items-center">
  <h1>編集</h1>
  <div class="ml-auto articles_button">
      <%= link_to '投稿一覧', articles_path, class: 'btn btn-outline-info' %>
  </div>
</div>
<%= form_for @article do |f| %>
    <div class="form-group">
        <%= f.label :name, '投稿者名' %>
        <%= f.text_field :name, class: 'form-control' %>
        <small id="poster-tip" class="form-text text-muted">
            あなたの名前を入力してください。
        </small>
    </div>
    <div class="form-group">
        <%= f.label :title, '投稿タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
        <small id="title-tip" class="form-text text-muted">
            タイトルを入力してください。
        </small>
         <div class="form-group">
        <%= f.label :place, '場所' %>
        <%= f.text_field :place, class: 'form-control' %>
        <small id="poster-tip" class="form-text text-muted">
            場所を入力してください。
        </small>
    </div>
    <div class="form-group">
        <%= f.label :learn, '学んだこと' %>
        <%= f.text_field :learn, class: 'form-control' %>
        <small id="poster-tip" class="form-text text-muted">
            学んだことを入力してください。
        </small>
    </div>
    <div class="form-group">
        <%= f.label :content, '投稿内容' %>
        <%= f.text_area :content, class: 'form-control', rows:10 %>
        <small id=content-tip" class="form-text text-muted">
            投稿内容を入力してください。 
        </small>
    </div>
    <%= f.submit '投稿', class: 'btn btn-info btn-block' %>
    <small id="submit-tip" class="form-text text-muted">
        投稿内容を確認してください。
    </small>
<% end %>

app/views/articles/new.html.erb
<%= render 'header' %>
<div class="d-flex align-items-center">
<h2>新規投稿</h2>
  <div class="ml-auto posts_button">
      <a class="btn btn-outline-info" href="/users/show/<%= current_user.id %>">マイページ</a>
  </div>
</div>
<%= form_for(@article, :url => { controller:'articles', action:'create'}) do |f| %>
    
    <div class="form-group">
        <%= f.label :title, '投稿タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
        <small id="title-tip" class="form-text text-muted">
            タイトルを入力してください。
        </small>
    </div>
    <div class="form-group">
        <%= f.label :place, '場所' %>
        <%= f.text_field :place, class: 'form-control' %>
        <small id="poster-tip" class="form-text text-muted">
            場所を入力してください。
        </small>
    </div>

    <div class="form-group">
        <%= f.label :content, '投稿内容' %>
        <%= f.text_area :content, class: 'form-control', rows:10 %>
        <small id="content-tip" class="form-text text-muted">
            投稿内容を入力してください。 
        </small>
    </div>
    <%= f.submit '投稿', class: 'btn btn-info btn-block' %>
    <small id="submit-tip" class="form-text text-muted">
        投稿内容を確認してください。
    </small>
<% end %>

app/views/articles/search.html.erb
<%= render 'header' %>
<%= form_tag({controller:"articles",action:"search"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索',:name => nil %>
  <% end %>
<table class="table table-bordered border-primary table-hover table-sm posts_table">
  <thead class="thead-dark">
    <tr>
      <th scope="col" style="background-color: #17a2b8 !important">No.</th>
      <th scope="col" style="background-color: #17a2b8 !important">投稿者</th>
      <th scope="col" style="background-color: #17a2b8 !important">投稿タイトル</th>
      <th scope="col" style="background-color: #17a2b8 !important">場所</th>
      <th scope="col" style="background-color: #17a2b8 !important">投稿日</th>
    </tr>
  </thead>
  <tbody>
　　　
      <% @search.each do |a| %>
          <tr>
              <td><a href="/articles/<%= a.id %>"><%= a.id %></a></td>
              <td><%= a.user.name %></td>
              <td><%= a.title %></td>
              <td><%= a.place %></td>
              <td><%= a.created_at.strftime('%Y/%m/%d %H:%M') %></td>
          </tr>        
      <% end %>
  </tbody>
</table>

app/views/articles/show.html.erb
<%= render 'header' %>
<div class="d-flex align-items-center mt-4 mb-4">
    <div class="ml-auto articles_button">
    <% if user_signed_in? %>
    <% if @article.user.id == current_user.id %>
      <div class="article-menus">
        <a class="btn btn-outline-info" href="/users/show" role="button">マイページ</a>
        <%= link_to '編集', edit_article_path(@article), class: "btn btn-outline-info" %>
        <%= link_to("削除", "/articles/:id", {method: "delete", class: "btn btn-outline-info"}) %>
      </div>
    <% end %>
    <% end %>
    </div>
</div>

<div class="main articles-show">
  <div class="container">
    <div class="articles-show-item">
    <h1><%= @article.title %></h1>
    <h3><%= @article.place %>あ</h3>
      <p>
        <%= simple_format (@article.content), :class=>"articles-content" %>
      </p>
      <div class="article-time">
        <%= @article.created_at %>
      </div>

      <div class="like-box">
      <% if user_signed_in? %>
        <% if current_user.already_liked?(@article) %>
          <%= link_to article_like_path(@article), {method: "delete"} do %>
          <span class="fa fa-heart like-btn-unlike"><%= @article.likes.count %></span>
          <% end %>
          <% @article.liked_users.each do |user| %>
            <p><%= user.name %></p>
            <% end %>
          
          
      <% else %>
          <%= link_to article_likes_path(@article), {method: "post"} do %>
          <span class="fa fa-heart like-btn-like"><%= @article.likes.count %></span>
          <% end %>
          <% @article.liked_users.each do |user| %>
            <p><%= user.name %></p>
            <% end %>
        <% end %>
      <% end %>
      </div>

    <% @comments.each do |c| %>
      <div>
        <a href="/users/<%= c.user.id %>"><%= c.user.name %></a>
        <%= c.content %>
        <hr>
      </div>
    <% end %>

<%= form_for [@article, @comment] do |f| %>
  <%= f.text_field :content %>
  <%= f.submit 'コメントする' %>
<% end %>





      