config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'
  get 'home/top' => 'home#top'
  get 'home/search' => 'home#search' 
  get 'home/about' => 'home#about'

  get 'articles/search' => 'articles#search'
  get "users/:id/likes" => "users#likes"
  get "articles/:id/likes" => "articles#likes"

  resources :articles, only: [:create, :index, :new, :show, :edit, :update, :destroy]do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "log_in", :to => "users/sessions#new"
    get "log_out", :to => "users/sessions#destroy" 
  end
  
  get "users/show/:id" => "users#show"
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_articles, through: :likes, source: :article
  has_many :comments

  validates :name, presence: true
  validates :profile, length: { maximum: 160 }

  def already_liked?(article)
    self.likes.exists?(article_id: article.id)
  end

  def articles
    return Article.where(user_id: self.id)
  end

  mount_uploader :imagename, ImagenameUploader
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    @articles = Article.where(user_id: @user.id)
    @allArticles = Article.all
  end

  def edit
    @user = User.find(params[:id])
  end

 
  def create
    if @user.save
      flash[:notice] = "登録に成功しました"
  else
      flash[:alert] = "登録に失敗しました"
    end
  end

  def update
    
      if current_user == @user
        if @user.update(user_params)
          flash[:success] = 'ユーザー情報を編集しました。'
          render :edit
          else
          flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
          render :edit
        end
      else
        redirect_to root_url
      end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
<a href="/users/<%= user.id %>"><%= user.email %></a>
<hr>
<% end %>
<%= link_to "ホームへ戻る", home_top_path %>

app/views/users/likes.html.erb
<table class="table table-bordered border-primary table-hover table-sm posts_table">
      <thead class="thead-dark">
        <tr>
          <th scope="col" style="width: 40px">No.</th>
          <th scope="col" style="width: 700px">投稿タイトル</th>
          <th scope="col">場所</th>
          <th scope="col">学んだこと</th>
          <th scope="col">投稿日</th>
          <th scope="col">更新日時</th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>　
  <% @likes.each do |like| %>
      <% article = Article.find_by(id: like.article_id) %>
      <tr>
        <th><%= a.id %></th>
          <td><%= a.title %></td>
          <td><%= a.place %></td>
          <td><%= a.learn %></td>
          <td><%= a.created_at.strftime('%Y/%m/%d %H:%M') %></td>
          <td><%= a.updated_at.strftime('%Y/%m/%d %H:%M') %></td>
          <td><%= link_to 'もっと見る', "/articles/#{a.id}" %><td>
      </tr>

app/views/users/profileedit.html.erb
<div class="edit-user">
  <h1 class="edit-user-header">Edit Profile</h1>
<div class="imagename-edit">
  <%= f.label :image %><br/>
  <%= f.file_field :imagename %>
 </div>

  <div class="edit-container">
    <%= f.text_area :profile, class: 'profile', value: 'write about yourself' %>
</div>    

app/views/users/show.html.erb
 <%= render 'header' %>
 <div class="background-image">
 <div class="d-flex align-items-center">
    
</div>

  <div class="user-wrap">
    <div class="image-current-user"><%= image_tag @user.imagename.to_s, class: "image" %></div>
    <div class="user-box">
      <h3 class="username"><%=  @user.name %></h3>
      <div class="posts_button">
        <a class="setting" href="/users/edit">設定</a>
        <a class="toukou" href="/articles/new">投稿</a>
      </div>
    </div>
  </div>


<ul class="tabnav">
    <li><a href="#tab01">プロフィール</a></li>
    <li><a href="#tab02">記事一覧</a></li>
    <li><a href="#tab03">いいね</a></li>
</ul>
</div>
<div class="tabcontent">
<div id="tab01">
<%= @user.profile %>
</div>
  <div id="tab02">
    <table class="table table-bordered border-primary table-hover table-sm posts_table">
      <thead class="thead-dark">
        <tr>
          <th scope="col" style="background-color: #17a2b8 !important">No.</th>
          <th scope="col" style="background-color: #17a2b8 !important">投稿タイトル</th>
          <th scope="col" style="background-color: #17a2b8 !important">場所</th>
          <th scope="col" style="background-color: #17a2b8 !important">投稿日</th>
          <th scope="col" style="background-color: #17a2b8 !important"></th>
        </tr>
      </thead>
      <tbody>　
        <% @articles.each do |a| %>
          
          <tr>
            <td><a href="/articles/<%= a.id %>"><%= a.id %></a></td>
            <td><%= a.title %></td>
            <td><%= a.place %></td>
            <td><%= a.created_at.strftime('%Y/%m/%d %H:%M') %></td>
            <td class="delete"><%= link_to "削除" , "/articles/#{a.id}", method: :delete %></td>
          </tr>
        </div>
        <% end %>
      </tbody>
    </table>
  </div>
  <div id="tab03">
  <table class="table table-bordered border-primary table-hover table-sm posts_table">
      <thead class="thead-dark">
        <tr>
          <th scope="col" style="background-color: #17a2b8 !important">No.</th>
          <th scope="col" style="background-color: #17a2b8 !important">投稿タイトル</th>
          <th scope="col" style="background-color: #17a2b8 !important">場所</th>
          <th scope="col" style="background-color: #17a2b8 !important">投稿日</th>
        </tr>
      </thead>
  <tbody>
  <% @allArticles.each do |a| %>
  <% if current_user.already_liked?(a) %> 
      <tr>
            <td><a href="/articles/<%= a.id %>"><%= a.id %></a></td>
            <td><%= a.title %></td>
            <td><%= a.place %></td>
            <td><%= a.created_at.strftime('%Y/%m/%d %H:%M') %></td>
          </tr>
  <% end %>
<% end %>
</tbody>
  </div>
 
  　
<script>
jQuery(function($){
    $('.tabcontent > div').hide();
 
    $('.tabnav a').click(function () {
        $('.tabcontent > div').hide();
        $('.tabcontent > div').filter(this.hash).fadeIn();
 
        $('.tabnav a').removeClass('active');
        $(this).addClass('active');
 
        return false;
    });
});
</script>