config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'
  get 'home/top' => 'home#top'
  get 'home/search' => 'home#search' 
  get 'home/about' => 'home#about'

  get 'articles/search' => 'articles#search'
  get "users/:id/likes" => "users#likes"
  get "articles/:id/likes" => "articles#likes"

  resources :articles, only: [:create, :index, :new, :show, :edit, :update, :destroy]do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "log_in", :to => "users/sessions#new"
    get "log_out", :to => "users/sessions#destroy" 
  end
  
  get "users/show/:id" => "users#show"
  resources :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_out_path_for(resource)
        root_path
    end

    def after_sign_in_path_for(resource)
      user_path(id: current_user.id)
    end

    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :imagename]) 
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :imagename, :profile]) 
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def header_link_item(name, path)
        class_name = 'nav-item'
        class_name << ' active' if current_page?(path)
        content_tag :li, class: class_name do
            link_to name, path, class: 'nav-link'
        end
    end
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="/home/top">Lit</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    <% if user_signed_in? %>
      <%= header_link_item('Mypage', user_path(id: current_user.id)) %>
      <% else %>
      <%= header_link_item('home', root_path) %>
      <% end %>
      <%= header_link_item('Search', articles_search_path) %>
      <%= header_link_item('Posts', new_article_path) %>
      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% else %>
        <%= link_to 'Login', new_user_session_path, method: :get, class: "nav-link" %>
      <% end %>
    </div>
  </div>
</nav>
<% if flash[:info] %>
  <p class="flash-notice"><i class="fas fa-check-square"></i> <%= flash[:info] %></p>
  <% end %>
  <script>
  $(function(){
  setTimeout("$('.flash-notice').fadeOut('slow')", 2000) 
})

</script>